version: "3.8"
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    depends_on: 
      - mysql_server
    links:
      - mysql_server
     
  mysql_server:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=kolyan28
    ports: 
      - 9992:3306 
